In [1]:
from pywhu3d.tool import WHU3D

data_root = '../data/whu3d-dataset'  
scenes = ['0010']
# whu3d = WHU3D(data_root=data_root, data_type='mls', format='txt')
whu3d = WHU3D(data_root=data_root, data_type='als', format='h5', scenes=scenes)

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


Output()

processing 0010...

Unknown Loading Error!

Num of scenes: 1

In [2]:
import h5py

In [3]:
f1 = h5py.File('../data/whu3d-dataset/als/h5/0020.h5')

In [4]:
f1.keys()

<KeysViewHDF5 ['coords', 'instances', 'semantics']>

In [5]:
f1['coords']

<HDF5 dataset "coords": shape (2639506, 3), type "<f8">

In [6]:
list(f1['coords'])

[array([6556.40625  , 3510.25     ,   18.4694519]),
 array([6556.375     , 3510.        ,   18.66745186]),
 array([6556.625     , 3510.25      ,   18.47345161]),
 array([6556.8125    , 3510.25      ,   18.45845222]),
 array([6557.        , 3510.25      ,   18.24845314]),
 array([6557.4375    , 3510.5       ,   18.10545158]),
 array([6557.65625  , 3510.75     ,   13.4304533]),
 array([6557.65625   , 3510.75      ,   13.81045341]),
 array([6557.65625  , 3510.5      ,   14.1804533]),
 array([6557.65625   , 3510.5       ,   14.57645321]),
 array([6557.65625   , 3510.5       ,   14.94145298]),
 array([6557.65625   , 3510.5       ,   15.33745384]),
 array([6557.65625   , 3510.5       ,   15.75545311]),
 array([6557.65625   , 3510.75      ,   16.13245201]),
 array([6557.65625  , 3510.75     ,   16.5394516]),
 array([6557.65625   , 3510.75      ,   16.90945244]),
 array([6557.65625   , 3510.75      ,   17.30245209]),
 array([6557.65625   , 3510.75      ,   17.69545174]),
 array([6557.875     ,

In [7]:
import numpy as np

In [8]:
np.array(f1['coords'])

array([[6556.40625   , 3510.25      ,   18.4694519 ],
       [6556.375     , 3510.        ,   18.66745186],
       [6556.625     , 3510.25      ,   18.47345161],
       ...,
       [6465.5       , 3361.5       ,   15.40457535],
       [6465.5       , 3361.5       ,   15.52357578],
       [6465.625     , 3361.5       ,   15.48357582]])

In [9]:
import open3d as o3d

In [ ]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(f1['coords'])

o3d.io.write_point_cloud("../data/whu3d-dataset/point_cloud.ply", pcd, print_progress=True)

In [24]:
set(f1['instances'])

{np.int64(15192822),
 np.int64(15193350),
 np.int64(15193417),
 np.int64(15193532),
 np.int64(15193540),
 np.int64(15193547),
 np.int64(15193620),
 np.int64(15193644),
 np.int64(15193715),
 np.int64(15193731),
 np.int64(15193754),
 np.int64(15193807),
 np.int64(15193815),
 np.int64(15193844),
 np.int64(15193912),
 np.int64(15193941),
 np.int64(15194230),
 np.int64(15194254),
 np.int64(15194337),
 np.int64(15194342),
 np.int64(15194457),
 np.int64(15194517),
 np.int64(15194957),
 np.int64(15195007),
 np.int64(15195014),
 np.int64(15195025),
 np.int64(15195032),
 np.int64(15195038),
 np.int64(15195124),
 np.int64(15195250),
 np.int64(15195306),
 np.int64(15195314),
 np.int64(15195324),
 np.int64(15195344),
 np.int64(15195415),
 np.int64(15195801),
 np.int64(15195832),
 np.int64(15195928),
 np.int64(15195959),
 np.int64(15200147),
 np.int64(15200204),
 np.int64(15200227),
 np.int64(15200236),
 np.int64(15200241),
 np.int64(15200320),
 np.int64(15200408),
 np.int64(15200416),
 np.int64(152

In [25]:
set(f1['semantics'])

{np.int64(100500),
 np.int64(200101),
 np.int64(200301),
 np.int64(200400),
 np.int64(200500),
 np.int64(200601),
 np.int64(200800),
 np.int64(200900)}

In [12]:
whu3d.scenes

['0010']

In [13]:
whu3d.list_attributes()

┏━━━━━━━━┳━━━━━━━━━━━┓
┃ groups ┃ attribute ┃
┡━━━━━━━━╇━━━━━━━━━━━┩
└────────┴───────────┘

[]