In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
input_path = '../data'
dataname = f"{input_path}/photshot-scene.ply"
pcd = o3d.io.read_point_cloud(dataname)

In [3]:
help(pcd)

Help on PointCloud in module open3d.cpu.pybind.geometry object:

class PointCloud(Geometry3D)
 |  PointCloud class. A point cloud consists of point coordinates, and optionally point colors and point normals.
 |  
 |  Method resolution order:
 |      PointCloud
 |      Geometry3D
 |      Geometry
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      __add__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.PointCloud
 |  
 |  __copy__(...)
 |      __copy__(self: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.PointCloud
 |  
 |  __deepcopy__(...)
 |      __deepcopy__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: dict) -> open3d.cpu.pybind.geometry.PointCloud
 |  
 |  __iadd__(...)
 |      __iadd__(self: open3d.cpu.pybind.geometry.PointCloud, arg0: open3d.cpu.pybind.geometry.PointCloud) -> open3d.cpu.pybind.geometry.Point

In [4]:
np.asarray(pcd.covariances)

array([], shape=(0, 3, 3), dtype=float64)

In [5]:
pcd.compute_mean_and_covariance()

(array([-0.38460363, -0.59323264,  0.42975375]),
 array([[4937.28347823,  -79.86555622, 1128.67483562],
        [ -79.86555622, 1938.73458911,  127.42989921],
        [1128.67483562,  127.42989921, 4237.60673698]]))

In [6]:
np.asarray(pcd.points)

array([[ 1.4015727 , -0.41441143,  1.30726492],
       [ 1.15383434, -0.36366251,  1.31640172],
       [ 1.2226522 , -2.19267964,  0.83250433],
       ...,
       [-1.76882148, -0.04426565, -0.76257074],
       [ 0.44738358, -0.58930528,  1.30630994],
       [ 0.45536444, -0.91613793, -4.16947079]])

In [14]:
pcd.estimate_covariances(search_param=o3d.geometry.KDTreeSearchParamKNN(knn=30))

Initialized covariances for Gaussian Splats

In [15]:
np.asarray(pcd.covariances).shape

(1196541, 3, 3)

In [16]:
np.asarray(pcd.covariances)

array([[[ 2.11519814e-05,  1.19639501e-05, -1.03522854e-05],
        [ 1.19639501e-05,  3.88200145e-05, -4.80258446e-06],
        [-1.03522854e-05, -4.80258446e-06,  2.26666842e-05]],

       [[ 5.32929568e-05,  4.09077841e-06, -1.57234782e-06],
        [ 4.09077841e-06,  2.64617524e-05, -1.22173228e-06],
        [-1.57234782e-06, -1.22173228e-06,  5.02601407e-06]],

       [[ 6.00863742e-03, -1.38604570e-03, -2.20416546e-04],
        [-1.38604570e-03,  5.85609706e-03, -1.24907830e-03],
        [-2.20416546e-04, -1.24907830e-03,  7.16912654e-03]],

       ...,

       [[ 4.67458236e-05,  8.42633399e-06, -1.06546983e-06],
        [ 8.42633399e-06,  3.17430570e-05, -1.11484980e-05],
        [-1.06546983e-06, -1.11484980e-05,  5.03509506e-05]],

       [[ 3.31732115e-04, -6.03256725e-05,  3.55679852e-05],
        [-6.03256725e-05,  9.41491529e-05,  2.53463424e-05],
        [ 3.55679852e-05,  2.53463424e-05,  1.13222786e-04]],

       [[ 2.29762706e-03, -2.77045949e-03,  2.45501137e-05],
 

In [10]:
# o3d.visualization.draw_geometries([pcd])