In [8]:
import pycolmap 
from pathlib import Path 
import numpy as np
from scipy.spatial.transform import Rotation as R

In [9]:
scene_folder = Path('../data/south-building')
images_folder = scene_folder / 'images'

database_path = scene_folder / 'database.db'

### Sparse Reconstruction

In [10]:
pycolmap.extract_features(database_path, images_folder, camera_model='SIMPLE_PINHOLE')
pycolmap.match_exhaustive(database_path)
maps = pycolmap.incremental_mapping(database_path, images_folder, scene_folder)
maps[0].write(scene_folder)

In [11]:
maps

{0: Reconstruction(num_reg_images=128, num_cameras=1, num_points3D=64668, num_observations=374741)}

Convert to PLY format, suitable for 3D data. (Sparse point cloud)

In [12]:
reconstruction = pycolmap.Reconstruction(scene_folder)

In [13]:
reconstruction.export_PLY(scene_folder / 'sparse.ply')

### Examining Reconstruction

In [14]:
reconstruction = pycolmap.Reconstruction(scene_folder / '0')
print(reconstruction.summary())

Reconstruction:
	num_reg_images = 128
	num_cameras = 1
	num_points3D = 64668
	num_observations = 374741
	mean_track_length = 5.79484
	mean_observations_per_image = 2927.66
	mean_reprojection_error = 0.750014


In [15]:
help(reconstruction)

Help on Reconstruction in module pycolmap object:

class Reconstruction(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Reconstruction
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __copy__(...)
 |      __copy__(self: pycolmap.Reconstruction) -> pycolmap.Reconstruction
 |
 |  __deepcopy__(...)
 |      __deepcopy__(self: pycolmap.Reconstruction, arg0: dict) -> pycolmap.Reconstruction
 |
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |
 |      1. __init__(self: pycolmap.Reconstruction) -> None
 |
 |      2. __init__(self: pycolmap.Reconstruction, sfm_dir: str) -> None
 |
 |  __repr__(...)
 |      __repr__(self: pycolmap.Reconstruction) -> str
 |
 |  add_camera(...)
 |      add_camera(self: pycolmap.Reconstruction, arg0: pycolmap.Camera) -> None
 |
 |      Add new camera. There is only one camera per image, while multiple images
 |      might be taken by the same camera.
 |
 

In [16]:
for image_id, image in reconstruction.images.items():
    print(image_id, image)

1 Image(image_id=1, camera_id=1, name="P1180141.JPG", triangulated=2395/12923)
2 Image(image_id=2, camera_id=1, name="P1180142.JPG", triangulated=2142/8620)
3 Image(image_id=3, camera_id=1, name="P1180143.JPG", triangulated=2054/8982)
4 Image(image_id=4, camera_id=1, name="P1180144.JPG", triangulated=1329/9548)
5 Image(image_id=5, camera_id=1, name="P1180145.JPG", triangulated=799/10334)
6 Image(image_id=6, camera_id=1, name="P1180146.JPG", triangulated=882/11774)
7 Image(image_id=7, camera_id=1, name="P1180147.JPG", triangulated=1038/9599)
8 Image(image_id=8, camera_id=1, name="P1180148.JPG", triangulated=956/7044)
9 Image(image_id=9, camera_id=1, name="P1180149.JPG", triangulated=1203/10432)
10 Image(image_id=10, camera_id=1, name="P1180150.JPG", triangulated=1064/10874)
11 Image(image_id=11, camera_id=1, name="P1180151.JPG", triangulated=784/6926)
12 Image(image_id=12, camera_id=1, name="P1180152.JPG", triangulated=639/6952)
13 Image(image_id=13, camera_id=1, name="P1180153.JPG", tr

In [17]:
img = reconstruction.images[1]

help(img)

Help on Image in module pycolmap object:

class Image(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Image
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __copy__(...)
 |      __copy__(self: pycolmap.Image) -> pycolmap.Image
 |
 |  __deepcopy__(...)
 |      __deepcopy__(self: pycolmap.Image, arg0: dict) -> pycolmap.Image
 |
 |  __getstate__(...)
 |      __getstate__(self: pycolmap.Image) -> dict
 |
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |
 |      1. __init__(self: pycolmap.Image) -> None
 |
 |      2. __init__(self: pycolmap.Image, name: str = '', points2D: List[colmap::Point2D] = [], cam_from_world: pycolmap.Rigid3d = Rigid3d(quat_xyzw=[0, 0, 0, 1], t=[0, 0, 0]), camera_id: int = 4294967295, id: int = 4294967295) -> None
 |
 |      3. __init__(self: pycolmap.Image, name: str = '', keypoints: numpy.ndarray[numpy.float64[m, 2]] = array([], shape=(0, 2), dtype=float6

In [18]:
img.points2D

[Point2D(xy=[2406.48, 226.915], point3D_id=Invalid),
 Point2D(xy=[2368.02, 240.081], point3D_id=Invalid),
 Point2D(xy=[2430.59, 246.949], point3D_id=64471),
 Point2D(xy=[2394.29, 257.213], point3D_id=Invalid),
 Point2D(xy=[2383.74, 261.567], point3D_id=Invalid),
 Point2D(xy=[2399.71, 261.81], point3D_id=63474),
 Point2D(xy=[2891.16, 267.467], point3D_id=Invalid),
 Point2D(xy=[2394.12, 270.269], point3D_id=64022),
 Point2D(xy=[2394.12, 270.269], point3D_id=Invalid),
 Point2D(xy=[1747.07, 272.561], point3D_id=68244),
 Point2D(xy=[2890.34, 276.551], point3D_id=Invalid),
 Point2D(xy=[2319.26, 288.113], point3D_id=64023),
 Point2D(xy=[2409.46, 289.643], point3D_id=65021),
 Point2D(xy=[2719.73, 292.837], point3D_id=63478),
 Point2D(xy=[2563.48, 293.414], point3D_id=65398),
 Point2D(xy=[2685.94, 293.363], point3D_id=Invalid),
 Point2D(xy=[2373.19, 296.502], point3D_id=Invalid),
 Point2D(xy=[1680.48, 297.669], point3D_id=Invalid),
 Point2D(xy=[2576.5, 297.421], point3D_id=Invalid),
 Point2D(xy

In [31]:
for point3D_id, point3D in reconstruction.points3D.items():
    print(point3D)

Point3D(xyz=[-0.303489, -0.538392, -0.390002], color=[180, 154, 145], error=0.832769, track=Track(length=2))
Point3D(xyz=[1.49456, 0.179941, 0.286854], color=[47, 89, 128], error=1.84298, track=Track(length=10))
Point3D(xyz=[-0.835134, -1.78012, -0.0289117], color=[166, 152, 140], error=0.258777, track=Track(length=4))
Point3D(xyz=[-1.0602, -1.73961, -0.103491], color=[109, 103, 103], error=0.514399, track=Track(length=6))
Point3D(xyz=[-1.88849, 0.47272, 1.27255], color=[80, 71, 72], error=0.246791, track=Track(length=3))
Point3D(xyz=[2.01107, 0.112806, -0.157884], color=[198, 167, 169], error=1.50211, track=Track(length=2))
Point3D(xyz=[-0.674547, -1.57285, -0.0896138], color=[113, 92, 90], error=0.285919, track=Track(length=5))
Point3D(xyz=[-1.04965, -0.890999, -0.294614], color=[115, 94, 93], error=0.683303, track=Track(length=5))
Point3D(xyz=[-2.83625, -0.937606, -0.0978741], color=[112, 93, 90], error=0.514418, track=Track(length=3))
Point3D(xyz=[-0.178052, -0.452439, -0.412057], 

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



### Camera

In [19]:
help(img.cam_from_world)

Help on Rigid3d in module pycolmap object:

class Rigid3d(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Rigid3d
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __copy__(...)
 |      __copy__(self: pycolmap.Rigid3d) -> pycolmap.Rigid3d
 |
 |  __deepcopy__(...)
 |      __deepcopy__(self: pycolmap.Rigid3d, arg0: dict) -> pycolmap.Rigid3d
 |
 |  __getstate__(...)
 |      __getstate__(self: pycolmap.Rigid3d) -> dict
 |
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |
 |      1. __init__(self: pycolmap.Rigid3d) -> None
 |
 |      2. __init__(self: pycolmap.Rigid3d, arg0: pycolmap.Rotation3d, arg1: numpy.ndarray[numpy.float64[3, 1]]) -> None
 |
 |      3. __init__(self: pycolmap.Rigid3d, arg0: numpy.ndarray[numpy.float64[3, 4]]) -> None
 |
 |      4. __init__(self: pycolmap.Rigid3d, arg0: dict) -> None
 |
 |      5. __init__(self: pycolmap.Rigid3d, **kwargs) -> None
 |
 |  __mul_

#### Extrinsic Matrix 
These are parameters that do not depend on the camera, they include **rotation** and **translation** (which don't depend on camera's build). The rotation can be expressed by quarternion (that uses only 4x1 matrix instead of 3x3 matrix). The translation vector tells the camera's position relative to the origin. 

\begin{pmatrix}
r_{11} & r_{12} & r_{13} & t_{x} \\
r_{21} & r_{22} & r_{23} & t_{y} \\
r_{31} & r_{32} & r_{33} & t_{z} \\
0 & 0 & 0 & 1
\end{pmatrix}

It is used to translate world coordinate system to camera coordinate system. 

In [20]:
print(img.cam_from_world)

Rigid3d(quat_xyzw=[0.0166735, 0.502906, -0.143915, 0.852113], t=[-0.672824, 0.96439, 3.59773])


In [21]:
print(reconstruction.images[10].cam_from_world)

Rigid3d(quat_xyzw=[0.00924112, 0.702713, -0.195956, 0.683894], t=[-0.534591, 0.951151, 3.49774])


In [22]:
print(img.cam_from_world.matrix()) # [R | t] matrix

[[ 0.45274845  0.26203346  0.85226599 -0.67282364]
 [-0.22849271  0.95802112 -0.17316644  0.96438993]
 [-0.86186421 -0.11633573  0.49361531  3.59773028]]


Essential matrix encapsulates the relative rotation and translation between two camera views.

In [23]:
print(img.cam_from_world.essential_matrix())

[[-0.00240898 -0.94025694  0.29036644]
 [ 0.27714073  0.22838756  0.89783834]
 [-0.0747395  -0.23706106 -0.18636774]]


In [24]:
img.cam_from_world.rotation.quat # rotation quaternion

array([ 0.01667347,  0.5029059 , -0.14391468,  0.8521128 ])

In [25]:
img.cam_from_world.translation # translation vector

array([-0.67282364,  0.96438993,  3.59773028])

In [26]:
reconstruction.images[10].cam_from_world.translation

array([-0.53459106,  0.95115122,  3.49774335])

In [27]:
for camera_id, camera in reconstruction.cameras.items():
    print(camera_id, camera)

1 Camera(camera_id=1, model=SIMPLE_PINHOLE, width=3072, height=2304, params=[2596.140252, 1536.000000, 1152.000000] (f, cx, cy))


#### Intrinsic matrix
This is needed to perform transformation between a point P in the 3D camera reference system to a point P' in the 2D image plane.

 \begin{pmatrix}
 fk & 0 & c_x & 0 \\
 0 & fk & c_y & 0 \\
 0 & 0 & 1 & 0 
 \end{pmatrix}
 
- f : focal length
- k : ratio $\frac{pixels}{cm}$ (digital images are expressed in pixels)
- $c_x$, $c_y$ : translation vector that describes offset between digital and camera coordinates

(this form of matrix is needed to make translations on 3D points)

In [32]:
reconstruction.cameras

{1: Camera(camera_id=1, model=SIMPLE_PINHOLE, width=3072, height=2304, params=[2596.140252, 1536.000000, 1152.000000] (f, cx, cy))}

In [34]:
point = reconstruction.points3D[2]
help(point.track)

Help on Track in module pycolmap object:

class Track(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Track
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __copy__(...)
 |      __copy__(self: pycolmap.Track) -> pycolmap.Track
 |
 |  __deepcopy__(...)
 |      __deepcopy__(self: pycolmap.Track, arg0: dict) -> pycolmap.Track
 |
 |  __getstate__(...)
 |      __getstate__(self: pycolmap.Track) -> dict
 |
 |  __init__(...)
 |      __init__(*args, **kwargs)
 |      Overloaded function.
 |
 |      1. __init__(self: pycolmap.Track) -> None
 |
 |      2. __init__(self: pycolmap.Track, arg0: List[pycolmap.TrackElement]) -> None
 |
 |      3. __init__(self: pycolmap.Track, arg0: dict) -> None
 |
 |      4. __init__(self: pycolmap.Track, **kwargs) -> None
 |
 |  __repr__(...)
 |      __repr__(self: pycolmap.Track) -> str
 |
 |  __setstate__(...)
 |      __setstate__(self: pycolmap.Track, arg0: dict) -> None
 |
 |  add_el

In [35]:
print(point.track.todict())

{'elements': [TrackElement(image_id=99, point2D_idx=12), TrackElement(image_id=72, point2D_idx=10), TrackElement(image_id=70, point2D_idx=7), TrackElement(image_id=69, point2D_idx=23), TrackElement(image_id=100, point2D_idx=3970), TrackElement(image_id=98, point2D_idx=10)]}


### Translation to image plane

In [36]:
points = np.array([point.xyz for point in reconstruction.points3D.values()]) 
points

array([[-0.30348886, -0.53839241, -0.3900015 ],
       [ 1.49455852,  0.17994117,  0.28685437],
       [-0.83513364, -1.78011518, -0.02891172],
       ...,
       [-1.69215032, -0.18830448, -0.78731384],
       [-2.90832941, -1.42818322,  0.13762155],
       [-2.79752025, -0.65786954,  1.43482166]])

In [37]:
img = reconstruction.images[1]
print(img.cam_from_world.rotation.quat)
print(img.cam_from_world.translation)

[ 0.01667347  0.5029059  -0.14391468  0.8521128 ]
[-0.67282364  0.96438993  3.59773028]


In [38]:
rot = R.from_quat(img.cam_from_world.rotation.quat)

In [39]:
rot.as_matrix()

array([[ 0.45274845,  0.26203346,  0.85226599],
       [-0.22849271,  0.95802112, -0.17316644],
       [-0.86186421, -0.11633573,  0.49361531]])

In [40]:
img.cam_from_world.matrix() # same as above

array([[ 0.45274845,  0.26203346,  0.85226599, -0.67282364],
       [-0.22849271,  0.95802112, -0.17316644,  0.96438993],
       [-0.86186421, -0.11633573,  0.49361531,  3.59773028]])

In [41]:
extrinsic_matrix = np.concatenate((img.cam_from_world.matrix(), np.array([[0, 0, 0, 1]])))
extrinsic_matrix

array([[ 0.45274845,  0.26203346,  0.85226599, -0.67282364],
       [-0.22849271,  0.95802112, -0.17316644,  0.96438993],
       [-0.86186421, -0.11633573,  0.49361531,  3.59773028],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

Convert points (expressed in world coordinates) to homogenous coordinates

In [42]:
ps = np.concatenate((points, np.ones((len(points), 1), np.float32)), axis=1)
ps

array([[-0.30348886, -0.53839241, -0.3900015 ,  1.        ],
       [ 1.49455852,  0.17994117,  0.28685437,  1.        ],
       [-0.83513364, -1.78011518, -0.02891172,  1.        ],
       ...,
       [-1.69215032, -0.18830448, -0.78731384,  1.        ],
       [-2.90832941, -1.42818322,  0.13762155,  1.        ],
       [-2.79752025, -0.65786954,  1.43482166,  1.        ]])

In [43]:
ps @ extrinsic_matrix

array([[ 0.32174297, -0.54994443, -0.35793245, -0.71814596],
       [ 0.38831429,  0.53064036,  1.38419732,  1.19998379],
       [ 0.05355586, -1.92085743, -0.41777106, -0.25884408],
       ...,
       [-0.04453461, -0.53220694, -1.7981843 , -0.87562302],
       [-1.10902327, -2.1463196 , -2.16342472,  2.0745925 ],
       [-2.35287601, -1.53021783, -1.56206049,  7.40989635]])

Problem: we should have pinhole camera model because it needs to work with gaussian splatting?

In [44]:
print(reconstruction.cameras[1])

Camera(camera_id=1, model=SIMPLE_PINHOLE, width=3072, height=2304, params=[2596.140252, 1536.000000, 1152.000000] (f, cx, cy))


In [45]:
f, cx, cy = reconstruction.cameras[1].params
intrinsic_matrix = np.array([[f, 0, cx, 0], [0, f, cy, 0], [0, 0, 1, 0]])

In [46]:
intrinsic_matrix

array([[2.59614025e+03, 0.00000000e+00, 1.53600000e+03, 0.00000000e+00],
       [0.00000000e+00, 2.59614025e+03, 1.15200000e+03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [47]:
projected_to_camera_viewpoint = (ps @ extrinsic_matrix).T

In [52]:
projected_to_camera_viewpoint.T[:10]

array([[ 3.21742968e-01, -5.49944431e-01, -3.57932450e-01,
        -7.18145957e-01],
       [ 3.88314291e-01,  5.30640363e-01,  1.38419732e+00,
         1.19998379e+00],
       [ 5.35558574e-02, -1.92085743e+00, -4.17771058e-01,
        -2.58844076e-01],
       [ 6.67875533e-03, -1.93235673e+00, -6.53418203e-01,
        -3.36669834e-01],
       [-2.05978866e+00, -1.90015120e-01, -1.06320786e+00,
         7.30479331e+00],
       [ 1.02080791e+00,  6.53405558e-01,  1.61649845e+00,
        -8.12330031e-01],
       [ 1.31219679e-01, -1.67315221e+00, -3.46763293e-01,
        -3.85396136e-01],
       [-1.77226428e-02, -1.09436434e+00, -8.85715077e-01,
        -2.12984410e-01],
       [-9.85518710e-01, -1.63005312e+00, -2.30319204e+00,
         1.65195549e+00],
       [ 3.77902934e-01, -4.32165132e-01, -2.76798187e-01,
        -7.98998432e-01]])

In [48]:
projected_to_image_plane = (intrinsic_matrix @ projected_to_camera_viewpoint).T

In [49]:
projected_to_image_plane.shape

(64668, 3)

These are still in homogeneous coordinates.

In [50]:
projected_to_image_plane[:10]

array([[ 2.85505627e+02, -1.84007106e+03, -3.57932450e-01],
       [ 3.13424545e+03,  2.97221212e+03,  1.38419732e+00],
       [-5.02657828e+02, -5.46808755e+03, -4.17771058e-01],
       [-9.86311375e+02, -5.76940687e+03, -6.53418203e-01],
       [-6.98058753e+03, -1.71812135e+03, -1.06320786e+00],
       [ 5.13310214e+03,  3.55853869e+03,  1.61649845e+00],
       [-1.91963728e+02, -4.74320912e+03, -3.46763293e-01],
       [-1.40646882e+03, -3.86146709e+03, -8.85715077e-01],
       [-6.09624776e+03, -6.88512374e+03, -2.30319204e+00],
       [ 5.55927002e+02, -1.44083280e+03, -2.76798187e-01]])